include:
    - project: pektin/pektin-dist
      ref: main
      file:
          - scripts/docker-build-and-publish.yml

image: alpine

variables:
    IMAGE_NAME: bind-alpine-docker

stages:
    - docker-build-and-publish
